name: Vitamix Trademark Audit
on:
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      PYTHONUNBUFFERED: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: requirements.txt

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Install browsers + OS deps for Ubuntu 24.04
      - name: Install Playwright browsers
        run: |
          python -m playwright install --with-deps chromium

      - name: Run audit
        run: |
          mkdir -p runs/out
          python -u audit.py \
            --urls-file top_urls_clean_us_en.csv \
            --marks-file trademarks_us_2025_text_only.json \
            --out runs/out \
            --concurrency 4 \
            --rps 2 \
            --save-flagged-screenshots

      - name: Upload results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: vitamix-audit-results
          path: runs/out
          if-no-files-found: error
